namespace DangKi_DangNhap
{
    partial class FormNhom
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormNhom));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            saveFileDialog1 = new SaveFileDialog();
            bunifuButton23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            bunifuButton27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            label1 = new Label();
            bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            listView1 = new ListView();
            textBox1 = new TextBox();
            richTextBox1 = new RichTextBox();
            bunifuButton25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            errorLabel = new Label();
            bunifuButton28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuPanel1.SuspendLayout();
            SuspendLayout();
            // 
            // saveFileDialog1
            // 
            saveFileDialog1.FileOk += saveFileDialog1_FileOk;
            // 
            // bunifuButton23
            // 
            bunifuButton23.AllowAnimations = true;
            bunifuButton23.AllowMouseEffects = true;
            bunifuButton23.AllowToggling = false;
            bunifuButton23.AnimationSpeed = 200;
            bunifuButton23.AutoGenerateColors = false;
            bunifuButton23.AutoRoundBorders = false;
            bunifuButton23.AutoSizeLeftIcon = true;
            bunifuButton23.AutoSizeRightIcon = true;
            bunifuButton23.BackColor = Color.Transparent;
            bunifuButton23.BackColor1 = Color.SteelBlue;
            bunifuButton23.BackgroundImage = (Image)resources.GetObject("bunifuButton23.BackgroundImage");
            bunifuButton23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.ButtonText = "Đăng";
            bunifuButton23.ButtonTextMarginLeft = 0;
            bunifuButton23.ColorContrastOnClick = 45;
            bunifuButton23.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            bunifuButton23.CustomizableEdges = borderEdges1;
            bunifuButton23.DialogResult = DialogResult.None;
            bunifuButton23.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton23.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton23.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton23.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton23.Font = new Font("Segoe UI", 9F);
            bunifuButton23.ForeColor = Color.White;
            bunifuButton23.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton23.IconLeftCursor = Cursors.Default;
            bunifuButton23.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton23.IconMarginLeft = 11;
            bunifuButton23.IconPadding = 10;
            bunifuButton23.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton23.IconRightCursor = Cursors.Default;
            bunifuButton23.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton23.IconSize = 25;
            bunifuButton23.IdleBorderColor = Color.Azure;
            bunifuButton23.IdleBorderRadius = 45;
            bunifuButton23.IdleBorderThickness = 2;
            bunifuButton23.IdleFillColor = Color.SteelBlue;
            bunifuButton23.IdleIconLeftImage = null;
            bunifuButton23.IdleIconRightImage = null;
            bunifuButton23.IndicateFocus = false;
            bunifuButton23.Location = new Point(560, 591);
            bunifuButton23.Name = "bunifuButton23";
            bunifuButton23.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton23.OnDisabledState.BorderRadius = 45;
            bunifuButton23.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.OnDisabledState.BorderThickness = 2;
            bunifuButton23.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton23.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton23.OnDisabledState.IconLeftImage = null;
            bunifuButton23.OnDisabledState.IconRightImage = null;
            bunifuButton23.onHoverState.BorderColor = Color.Cyan;
            bunifuButton23.onHoverState.BorderRadius = 45;
            bunifuButton23.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.onHoverState.BorderThickness = 2;
            bunifuButton23.onHoverState.FillColor = Color.Cyan;
            bunifuButton23.onHoverState.ForeColor = Color.White;
            bunifuButton23.onHoverState.IconLeftImage = null;
            bunifuButton23.onHoverState.IconRightImage = null;
            bunifuButton23.OnIdleState.BorderColor = Color.Azure;
            bunifuButton23.OnIdleState.BorderRadius = 45;
            bunifuButton23.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.OnIdleState.BorderThickness = 2;
            bunifuButton23.OnIdleState.FillColor = Color.SteelBlue;
            bunifuButton23.OnIdleState.ForeColor = Color.White;
            bunifuButton23.OnIdleState.IconLeftImage = null;
            bunifuButton23.OnIdleState.IconRightImage = null;
            bunifuButton23.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton23.OnPressedState.BorderRadius = 45;
            bunifuButton23.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.OnPressedState.BorderThickness = 2;
            bunifuButton23.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton23.OnPressedState.ForeColor = Color.White;
            bunifuButton23.OnPressedState.IconLeftImage = null;
            bunifuButton23.OnPressedState.IconRightImage = null;
            bunifuButton23.Size = new Size(101, 62);
            bunifuButton23.TabIndex = 18;
            bunifuButton23.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton23.TextAlignment = HorizontalAlignment.Center;
            bunifuButton23.TextMarginLeft = 0;
            bunifuButton23.TextPadding = new Padding(0);
            bunifuButton23.UseDefaultRadiusAndThickness = true;
            bunifuButton23.Click += bunifuButton23_Click;
            // 
            // bunifuButton22
            // 
            bunifuButton22.AllowAnimations = true;
            bunifuButton22.AllowMouseEffects = true;
            bunifuButton22.AllowToggling = false;
            bunifuButton22.AnimationSpeed = 200;
            bunifuButton22.AutoGenerateColors = false;
            bunifuButton22.AutoRoundBorders = false;
            bunifuButton22.AutoSizeLeftIcon = true;
            bunifuButton22.AutoSizeRightIcon = true;
            bunifuButton22.BackColor = Color.Transparent;
            bunifuButton22.BackColor1 = Color.SteelBlue;
            bunifuButton22.BackgroundImage = (Image)resources.GetObject("bunifuButton22.BackgroundImage");
            bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.ButtonText = "Chọn File";
            bunifuButton22.ButtonTextMarginLeft = 0;
            bunifuButton22.ColorContrastOnClick = 45;
            bunifuButton22.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            bunifuButton22.CustomizableEdges = borderEdges2;
            bunifuButton22.DialogResult = DialogResult.None;
            bunifuButton22.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton22.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton22.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton22.Font = new Font("Segoe UI", 9F);
            bunifuButton22.ForeColor = Color.White;
            bunifuButton22.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton22.IconLeftCursor = Cursors.Default;
            bunifuButton22.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton22.IconMarginLeft = 11;
            bunifuButton22.IconPadding = 10;
            bunifuButton22.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton22.IconRightCursor = Cursors.Default;
            bunifuButton22.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton22.IconSize = 25;
            bunifuButton22.IdleBorderColor = Color.Azure;
            bunifuButton22.IdleBorderRadius = 45;
            bunifuButton22.IdleBorderThickness = 2;
            bunifuButton22.IdleFillColor = Color.SteelBlue;
            bunifuButton22.IdleIconLeftImage = null;
            bunifuButton22.IdleIconRightImage = null;
            bunifuButton22.IndicateFocus = false;
            bunifuButton22.Location = new Point(1072, 659);
            bunifuButton22.Name = "bunifuButton22";
            bunifuButton22.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton22.OnDisabledState.BorderRadius = 45;
            bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnDisabledState.BorderThickness = 2;
            bunifuButton22.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton22.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton22.OnDisabledState.IconLeftImage = null;
            bunifuButton22.OnDisabledState.IconRightImage = null;
            bunifuButton22.onHoverState.BorderColor = Color.Cyan;
            bunifuButton22.onHoverState.BorderRadius = 45;
            bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.onHoverState.BorderThickness = 2;
            bunifuButton22.onHoverState.FillColor = Color.Cyan;
            bunifuButton22.onHoverState.ForeColor = Color.White;
            bunifuButton22.onHoverState.IconLeftImage = null;
            bunifuButton22.onHoverState.IconRightImage = null;
            bunifuButton22.OnIdleState.BorderColor = Color.Azure;
            bunifuButton22.OnIdleState.BorderRadius = 45;
            bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnIdleState.BorderThickness = 2;
            bunifuButton22.OnIdleState.FillColor = Color.SteelBlue;
            bunifuButton22.OnIdleState.ForeColor = Color.White;
            bunifuButton22.OnIdleState.IconLeftImage = null;
            bunifuButton22.OnIdleState.IconRightImage = null;
            bunifuButton22.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton22.OnPressedState.BorderRadius = 45;
            bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnPressedState.BorderThickness = 2;
            bunifuButton22.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton22.OnPressedState.ForeColor = Color.White;
            bunifuButton22.OnPressedState.IconLeftImage = null;
            bunifuButton22.OnPressedState.IconRightImage = null;
            bunifuButton22.Size = new Size(100, 62);
            bunifuButton22.TabIndex = 17;
            bunifuButton22.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton22.TextAlignment = HorizontalAlignment.Center;
            bunifuButton22.TextMarginLeft = 0;
            bunifuButton22.TextPadding = new Padding(0);
            bunifuButton22.UseDefaultRadiusAndThickness = true;
            bunifuButton22.Click += bunifuButton22_Click;
            // 
            // bunifuPanel1
            // 
            bunifuPanel1.BackgroundColor = Color.SteelBlue;
            bunifuPanel1.BackgroundImage = (Image)resources.GetObject("bunifuPanel1.BackgroundImage");
            bunifuPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel1.BorderColor = Color.MidnightBlue;
            bunifuPanel1.BorderRadius = 30;
            bunifuPanel1.BorderThickness = 2;
            bunifuPanel1.Controls.Add(bunifuButton27);
            bunifuPanel1.Controls.Add(bunifuButton24);
            bunifuPanel1.Controls.Add(label1);
            bunifuPanel1.Controls.Add(bunifuButton21);
            bunifuPanel1.Controls.Add(listView1);
            bunifuPanel1.Location = new Point(677, 18);
            bunifuPanel1.Name = "bunifuPanel1";
            bunifuPanel1.ShowBorders = true;
            bunifuPanel1.Size = new Size(391, 483);
            bunifuPanel1.TabIndex = 16;
            // 
            // bunifuButton27
            // 
            bunifuButton27.AllowAnimations = true;
            bunifuButton27.AllowMouseEffects = true;
            bunifuButton27.AllowToggling = false;
            bunifuButton27.AnimationSpeed = 200;
            bunifuButton27.AutoGenerateColors = false;
            bunifuButton27.AutoRoundBorders = false;
            bunifuButton27.AutoSizeLeftIcon = true;
            bunifuButton27.AutoSizeRightIcon = true;
            bunifuButton27.BackColor = Color.Transparent;
            bunifuButton27.BackColor1 = Color.Red;
            bunifuButton27.BackgroundImage = (Image)resources.GetObject("bunifuButton27.BackgroundImage");
            bunifuButton27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.ButtonText = "Xóa nhóm";
            bunifuButton27.ButtonTextMarginLeft = 0;
            bunifuButton27.ColorContrastOnClick = 45;
            bunifuButton27.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            bunifuButton27.CustomizableEdges = borderEdges3;
            bunifuButton27.DialogResult = DialogResult.None;
            bunifuButton27.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton27.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton27.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton27.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton27.Font = new Font("Segoe UI", 9F);
            bunifuButton27.ForeColor = Color.White;
            bunifuButton27.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton27.IconLeftCursor = Cursors.Default;
            bunifuButton27.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton27.IconMarginLeft = 11;
            bunifuButton27.IconPadding = 10;
            bunifuButton27.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton27.IconRightCursor = Cursors.Default;
            bunifuButton27.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton27.IconSize = 25;
            bunifuButton27.IdleBorderColor = Color.Azure;
            bunifuButton27.IdleBorderRadius = 45;
            bunifuButton27.IdleBorderThickness = 2;
            bunifuButton27.IdleFillColor = Color.Red;
            bunifuButton27.IdleIconLeftImage = null;
            bunifuButton27.IdleIconRightImage = null;
            bunifuButton27.IndicateFocus = false;
            bunifuButton27.Location = new Point(141, 375);
            bunifuButton27.Name = "bunifuButton27";
            bunifuButton27.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton27.OnDisabledState.BorderRadius = 45;
            bunifuButton27.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnDisabledState.BorderThickness = 2;
            bunifuButton27.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton27.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton27.OnDisabledState.IconLeftImage = null;
            bunifuButton27.OnDisabledState.IconRightImage = null;
            bunifuButton27.onHoverState.BorderColor = Color.Cyan;
            bunifuButton27.onHoverState.BorderRadius = 45;
            bunifuButton27.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.onHoverState.BorderThickness = 2;
            bunifuButton27.onHoverState.FillColor = Color.Cyan;
            bunifuButton27.onHoverState.ForeColor = Color.White;
            bunifuButton27.onHoverState.IconLeftImage = null;
            bunifuButton27.onHoverState.IconRightImage = null;
            bunifuButton27.OnIdleState.BorderColor = Color.Azure;
            bunifuButton27.OnIdleState.BorderRadius = 45;
            bunifuButton27.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnIdleState.BorderThickness = 2;
            bunifuButton27.OnIdleState.FillColor = Color.Red;
            bunifuButton27.OnIdleState.ForeColor = Color.White;
            bunifuButton27.OnIdleState.IconLeftImage = null;
            bunifuButton27.OnIdleState.IconRightImage = null;
            bunifuButton27.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton27.OnPressedState.BorderRadius = 45;
            bunifuButton27.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnPressedState.BorderThickness = 2;
            bunifuButton27.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton27.OnPressedState.ForeColor = Color.White;
            bunifuButton27.OnPressedState.IconLeftImage = null;
            bunifuButton27.OnPressedState.IconRightImage = null;
            bunifuButton27.Size = new Size(117, 83);
            bunifuButton27.TabIndex = 12;
            bunifuButton27.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton27.TextAlignment = HorizontalAlignment.Center;
            bunifuButton27.TextMarginLeft = 0;
            bunifuButton27.TextPadding = new Padding(0);
            bunifuButton27.UseDefaultRadiusAndThickness = true;
            bunifuButton27.Click += bunifuButton27_Click;
            // 
            // bunifuButton24
            // 
            bunifuButton24.AllowAnimations = true;
            bunifuButton24.AllowMouseEffects = true;
            bunifuButton24.AllowToggling = false;
            bunifuButton24.AnimationSpeed = 200;
            bunifuButton24.AutoGenerateColors = false;
            bunifuButton24.AutoRoundBorders = false;
            bunifuButton24.AutoSizeLeftIcon = true;
            bunifuButton24.AutoSizeRightIcon = true;
            bunifuButton24.BackColor = Color.Transparent;
            bunifuButton24.BackColor1 = Color.SteelBlue;
            bunifuButton24.BackgroundImage = (Image)resources.GetObject("bunifuButton24.BackgroundImage");
            bunifuButton24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.ButtonText = "Mời";
            bunifuButton24.ButtonTextMarginLeft = 0;
            bunifuButton24.ColorContrastOnClick = 45;
            bunifuButton24.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            bunifuButton24.CustomizableEdges = borderEdges4;
            bunifuButton24.DialogResult = DialogResult.None;
            bunifuButton24.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton24.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton24.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton24.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton24.Font = new Font("Segoe UI", 9F);
            bunifuButton24.ForeColor = Color.White;
            bunifuButton24.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton24.IconLeftCursor = Cursors.Default;
            bunifuButton24.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton24.IconMarginLeft = 11;
            bunifuButton24.IconPadding = 10;
            bunifuButton24.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton24.IconRightCursor = Cursors.Default;
            bunifuButton24.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton24.IconSize = 25;
            bunifuButton24.IdleBorderColor = Color.Azure;
            bunifuButton24.IdleBorderRadius = 45;
            bunifuButton24.IdleBorderThickness = 2;
            bunifuButton24.IdleFillColor = Color.SteelBlue;
            bunifuButton24.IdleIconLeftImage = null;
            bunifuButton24.IdleIconRightImage = null;
            bunifuButton24.IndicateFocus = false;
            bunifuButton24.Location = new Point(28, 375);
            bunifuButton24.Name = "bunifuButton24";
            bunifuButton24.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton24.OnDisabledState.BorderRadius = 45;
            bunifuButton24.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.OnDisabledState.BorderThickness = 2;
            bunifuButton24.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton24.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton24.OnDisabledState.IconLeftImage = null;
            bunifuButton24.OnDisabledState.IconRightImage = null;
            bunifuButton24.onHoverState.BorderColor = Color.Cyan;
            bunifuButton24.onHoverState.BorderRadius = 45;
            bunifuButton24.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.onHoverState.BorderThickness = 2;
            bunifuButton24.onHoverState.FillColor = Color.Cyan;
            bunifuButton24.onHoverState.ForeColor = Color.White;
            bunifuButton24.onHoverState.IconLeftImage = null;
            bunifuButton24.onHoverState.IconRightImage = null;
            bunifuButton24.OnIdleState.BorderColor = Color.Azure;
            bunifuButton24.OnIdleState.BorderRadius = 45;
            bunifuButton24.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.OnIdleState.BorderThickness = 2;
            bunifuButton24.OnIdleState.FillColor = Color.SteelBlue;
            bunifuButton24.OnIdleState.ForeColor = Color.White;
            bunifuButton24.OnIdleState.IconLeftImage = null;
            bunifuButton24.OnIdleState.IconRightImage = null;
            bunifuButton24.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton24.OnPressedState.BorderRadius = 45;
            bunifuButton24.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.OnPressedState.BorderThickness = 2;
            bunifuButton24.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton24.OnPressedState.ForeColor = Color.White;
            bunifuButton24.OnPressedState.IconLeftImage = null;
            bunifuButton24.OnPressedState.IconRightImage = null;
            bunifuButton24.Size = new Size(107, 83);
            bunifuButton24.TabIndex = 11;
            bunifuButton24.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton24.TextAlignment = HorizontalAlignment.Center;
            bunifuButton24.TextMarginLeft = 0;
            bunifuButton24.TextPadding = new Padding(0);
            bunifuButton24.UseDefaultRadiusAndThickness = true;
            bunifuButton24.Click += bunifuButton24_Click;
            // 
            // label1
            // 
            label1.BackColor = Color.Transparent;
            label1.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.White;
            label1.Location = new Point(72, 30);
            label1.Name = "label1";
            label1.Size = new Size(253, 33);
            label1.TabIndex = 10;
            label1.Text = "Danh sách thành viên ";
            label1.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // bunifuButton21
            // 
            bunifuButton21.AllowAnimations = true;
            bunifuButton21.AllowMouseEffects = true;
            bunifuButton21.AllowToggling = false;
            bunifuButton21.AnimationSpeed = 200;
            bunifuButton21.AutoGenerateColors = false;
            bunifuButton21.AutoRoundBorders = false;
            bunifuButton21.AutoSizeLeftIcon = true;
            bunifuButton21.AutoSizeRightIcon = true;
            bunifuButton21.BackColor = Color.Transparent;
            bunifuButton21.BackColor1 = Color.DodgerBlue;
            bunifuButton21.BackgroundImage = (Image)resources.GetObject("bunifuButton21.BackgroundImage");
            bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.ButtonText = "Rời Nhóm";
            bunifuButton21.ButtonTextMarginLeft = 0;
            bunifuButton21.ColorContrastOnClick = 45;
            bunifuButton21.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            bunifuButton21.CustomizableEdges = borderEdges5;
            bunifuButton21.DialogResult = DialogResult.None;
            bunifuButton21.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton21.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton21.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton21.Font = new Font("Segoe UI", 9F);
            bunifuButton21.ForeColor = Color.White;
            bunifuButton21.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton21.IconLeftCursor = Cursors.Default;
            bunifuButton21.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton21.IconMarginLeft = 11;
            bunifuButton21.IconPadding = 10;
            bunifuButton21.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton21.IconRightCursor = Cursors.Default;
            bunifuButton21.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton21.IconSize = 25;
            bunifuButton21.IdleBorderColor = Color.Azure;
            bunifuButton21.IdleBorderRadius = 45;
            bunifuButton21.IdleBorderThickness = 2;
            bunifuButton21.IdleFillColor = Color.DodgerBlue;
            bunifuButton21.IdleIconLeftImage = null;
            bunifuButton21.IdleIconRightImage = null;
            bunifuButton21.IndicateFocus = false;
            bunifuButton21.Location = new Point(264, 375);
            bunifuButton21.Name = "bunifuButton21";
            bunifuButton21.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton21.OnDisabledState.BorderRadius = 45;
            bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnDisabledState.BorderThickness = 2;
            bunifuButton21.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton21.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton21.OnDisabledState.IconLeftImage = null;
            bunifuButton21.OnDisabledState.IconRightImage = null;
            bunifuButton21.onHoverState.BorderColor = Color.Tomato;
            bunifuButton21.onHoverState.BorderRadius = 45;
            bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.onHoverState.BorderThickness = 2;
            bunifuButton21.onHoverState.FillColor = Color.Tomato;
            bunifuButton21.onHoverState.ForeColor = Color.White;
            bunifuButton21.onHoverState.IconLeftImage = null;
            bunifuButton21.onHoverState.IconRightImage = null;
            bunifuButton21.OnIdleState.BorderColor = Color.Azure;
            bunifuButton21.OnIdleState.BorderRadius = 45;
            bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnIdleState.BorderThickness = 2;
            bunifuButton21.OnIdleState.FillColor = Color.DodgerBlue;
            bunifuButton21.OnIdleState.ForeColor = Color.White;
            bunifuButton21.OnIdleState.IconLeftImage = null;
            bunifuButton21.OnIdleState.IconRightImage = null;
            bunifuButton21.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton21.OnPressedState.BorderRadius = 45;
            bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnPressedState.BorderThickness = 2;
            bunifuButton21.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton21.OnPressedState.ForeColor = Color.White;
            bunifuButton21.OnPressedState.IconLeftImage = null;
            bunifuButton21.OnPressedState.IconRightImage = null;
            bunifuButton21.Size = new Size(100, 83);
            bunifuButton21.TabIndex = 9;
            bunifuButton21.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton21.TextAlignment = HorizontalAlignment.Center;
            bunifuButton21.TextMarginLeft = 0;
            bunifuButton21.TextPadding = new Padding(0);
            bunifuButton21.UseDefaultRadiusAndThickness = true;
            bunifuButton21.Click += bunifuButton21_Click;
            // 
            // listView1
            // 
            listView1.BackColor = Color.OldLace;
            listView1.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            listView1.Location = new Point(28, 66);
            listView1.Name = "listView1";
            listView1.Size = new Size(336, 303);
            listView1.TabIndex = 0;
            listView1.UseCompatibleStateImageBehavior = false;
            listView1.View = View.Details;
            // 
            // textBox1
            // 
            textBox1.BackColor = Color.OldLace;
            textBox1.Font = new Font("Segoe UI", 10.2F, FontStyle.Regular, GraphicsUnit.Point, 0);
            textBox1.Location = new Point(130, 594);
            textBox1.Multiline = true;
            textBox1.Name = "textBox1";
            textBox1.Size = new Size(418, 62);
            textBox1.TabIndex = 13;
            // 
            // richTextBox1
            // 
            richTextBox1.BackColor = Color.OldLace;
            richTextBox1.Font = new Font("Segoe UI Emoji", 10.2F, FontStyle.Regular, GraphicsUnit.Point, 0);
            richTextBox1.Location = new Point(19, 18);
            richTextBox1.Margin = new Padding(0);
            richTextBox1.Name = "richTextBox1";
            richTextBox1.ReadOnly = true;
            richTextBox1.Size = new Size(642, 540);
            richTextBox1.TabIndex = 14;
            richTextBox1.Text = "";
            // 
            // bunifuButton25
            // 
            bunifuButton25.AllowAnimations = true;
            bunifuButton25.AllowMouseEffects = true;
            bunifuButton25.AllowToggling = false;
            bunifuButton25.AnimationSpeed = 200;
            bunifuButton25.AutoGenerateColors = false;
            bunifuButton25.AutoRoundBorders = false;
            bunifuButton25.AutoSizeLeftIcon = true;
            bunifuButton25.AutoSizeRightIcon = true;
            bunifuButton25.BackColor = Color.Transparent;
            bunifuButton25.BackColor1 = Color.SteelBlue;
            bunifuButton25.BackgroundImage = (Image)resources.GetObject("bunifuButton25.BackgroundImage");
            bunifuButton25.BackgroundImageLayout = ImageLayout.Zoom;
            bunifuButton25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.ButtonText = "Kho tài liệu";
            bunifuButton25.ButtonTextMarginLeft = 0;
            bunifuButton25.ColorContrastOnClick = 45;
            bunifuButton25.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            bunifuButton25.CustomizableEdges = borderEdges6;
            bunifuButton25.DialogResult = DialogResult.None;
            bunifuButton25.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton25.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton25.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton25.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton25.Font = new Font("Segoe UI", 9F);
            bunifuButton25.ForeColor = Color.White;
            bunifuButton25.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton25.IconLeftCursor = Cursors.Default;
            bunifuButton25.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton25.IconMarginLeft = 11;
            bunifuButton25.IconPadding = 10;
            bunifuButton25.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton25.IconRightCursor = Cursors.Default;
            bunifuButton25.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton25.IconSize = 25;
            bunifuButton25.IdleBorderColor = Color.Azure;
            bunifuButton25.IdleBorderRadius = 30;
            bunifuButton25.IdleBorderThickness = 2;
            bunifuButton25.IdleFillColor = Color.SteelBlue;
            bunifuButton25.IdleIconLeftImage = null;
            bunifuButton25.IdleIconRightImage = null;
            bunifuButton25.IndicateFocus = false;
            bunifuButton25.Location = new Point(718, 507);
            bunifuButton25.Name = "bunifuButton25";
            bunifuButton25.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton25.OnDisabledState.BorderRadius = 30;
            bunifuButton25.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.OnDisabledState.BorderThickness = 2;
            bunifuButton25.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton25.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton25.OnDisabledState.IconLeftImage = null;
            bunifuButton25.OnDisabledState.IconRightImage = null;
            bunifuButton25.onHoverState.BorderColor = Color.Cyan;
            bunifuButton25.onHoverState.BorderRadius = 30;
            bunifuButton25.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.onHoverState.BorderThickness = 2;
            bunifuButton25.onHoverState.FillColor = Color.Cyan;
            bunifuButton25.onHoverState.ForeColor = Color.White;
            bunifuButton25.onHoverState.IconLeftImage = null;
            bunifuButton25.onHoverState.IconRightImage = null;
            bunifuButton25.OnIdleState.BorderColor = Color.Azure;
            bunifuButton25.OnIdleState.BorderRadius = 30;
            bunifuButton25.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.OnIdleState.BorderThickness = 2;
            bunifuButton25.OnIdleState.FillColor = Color.SteelBlue;
            bunifuButton25.OnIdleState.ForeColor = Color.White;
            bunifuButton25.OnIdleState.IconLeftImage = null;
            bunifuButton25.OnIdleState.IconRightImage = null;
            bunifuButton25.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton25.OnPressedState.BorderRadius = 30;
            bunifuButton25.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.OnPressedState.BorderThickness = 2;
            bunifuButton25.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton25.OnPressedState.ForeColor = Color.White;
            bunifuButton25.OnPressedState.IconLeftImage = null;
            bunifuButton25.OnPressedState.IconRightImage = null;
            bunifuButton25.Size = new Size(323, 51);
            bunifuButton25.TabIndex = 19;
            bunifuButton25.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton25.TextAlignment = HorizontalAlignment.Center;
            bunifuButton25.TextMarginLeft = 0;
            bunifuButton25.TextPadding = new Padding(0);
            bunifuButton25.UseDefaultRadiusAndThickness = true;
            bunifuButton25.Click += bunifuButton25_Click;
            // 
            // bunifuButton26
            // 
            bunifuButton26.AllowAnimations = true;
            bunifuButton26.AllowMouseEffects = true;
            bunifuButton26.AllowToggling = false;
            bunifuButton26.AnimationSpeed = 200;
            bunifuButton26.AutoGenerateColors = false;
            bunifuButton26.AutoRoundBorders = false;
            bunifuButton26.AutoSizeLeftIcon = true;
            bunifuButton26.AutoSizeRightIcon = true;
            bunifuButton26.BackColor = Color.Transparent;
            bunifuButton26.BackColor1 = Color.SteelBlue;
            bunifuButton26.BackgroundImage = (Image)resources.GetObject("bunifuButton26.BackgroundImage");
            bunifuButton26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.ButtonText = "icon";
            bunifuButton26.ButtonTextMarginLeft = 0;
            bunifuButton26.ColorContrastOnClick = 45;
            bunifuButton26.ColorContrastOnHover = 45;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            bunifuButton26.CustomizableEdges = borderEdges7;
            bunifuButton26.DialogResult = DialogResult.None;
            bunifuButton26.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton26.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton26.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton26.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton26.Font = new Font("Segoe UI", 9F);
            bunifuButton26.ForeColor = Color.White;
            bunifuButton26.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton26.IconLeftCursor = Cursors.Default;
            bunifuButton26.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton26.IconMarginLeft = 11;
            bunifuButton26.IconPadding = 10;
            bunifuButton26.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton26.IconRightCursor = Cursors.Default;
            bunifuButton26.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton26.IconSize = 25;
            bunifuButton26.IdleBorderColor = Color.Azure;
            bunifuButton26.IdleBorderRadius = 45;
            bunifuButton26.IdleBorderThickness = 2;
            bunifuButton26.IdleFillColor = Color.SteelBlue;
            bunifuButton26.IdleIconLeftImage = null;
            bunifuButton26.IdleIconRightImage = null;
            bunifuButton26.IndicateFocus = false;
            bunifuButton26.Location = new Point(19, 595);
            bunifuButton26.Name = "bunifuButton26";
            bunifuButton26.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton26.OnDisabledState.BorderRadius = 45;
            bunifuButton26.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.OnDisabledState.BorderThickness = 2;
            bunifuButton26.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton26.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton26.OnDisabledState.IconLeftImage = null;
            bunifuButton26.OnDisabledState.IconRightImage = null;
            bunifuButton26.onHoverState.BorderColor = Color.Cyan;
            bunifuButton26.onHoverState.BorderRadius = 45;
            bunifuButton26.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.onHoverState.BorderThickness = 2;
            bunifuButton26.onHoverState.FillColor = Color.Cyan;
            bunifuButton26.onHoverState.ForeColor = Color.White;
            bunifuButton26.onHoverState.IconLeftImage = null;
            bunifuButton26.onHoverState.IconRightImage = null;
            bunifuButton26.OnIdleState.BorderColor = Color.Azure;
            bunifuButton26.OnIdleState.BorderRadius = 45;
            bunifuButton26.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.OnIdleState.BorderThickness = 2;
            bunifuButton26.OnIdleState.FillColor = Color.SteelBlue;
            bunifuButton26.OnIdleState.ForeColor = Color.White;
            bunifuButton26.OnIdleState.IconLeftImage = null;
            bunifuButton26.OnIdleState.IconRightImage = null;
            bunifuButton26.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton26.OnPressedState.BorderRadius = 45;
            bunifuButton26.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.OnPressedState.BorderThickness = 2;
            bunifuButton26.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton26.OnPressedState.ForeColor = Color.White;
            bunifuButton26.OnPressedState.IconLeftImage = null;
            bunifuButton26.OnPressedState.IconRightImage = null;
            bunifuButton26.Size = new Size(101, 62);
            bunifuButton26.TabIndex = 20;
            bunifuButton26.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton26.TextAlignment = HorizontalAlignment.Center;
            bunifuButton26.TextMarginLeft = 0;
            bunifuButton26.TextPadding = new Padding(0);
            bunifuButton26.UseDefaultRadiusAndThickness = true;
            bunifuButton26.Click += bunifuButton26_Click;
            // 
            // errorLabel
            // 
            errorLabel.BackColor = Color.LightBlue;
            errorLabel.Font = new Font("Segoe UI", 10.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            errorLabel.ForeColor = Color.Red;
            errorLabel.Location = new Point(22, 562);
            errorLabel.Name = "errorLabel";
            errorLabel.Size = new Size(192, 28);
            errorLabel.TabIndex = 29;
            errorLabel.Text = "errorLabel";
            errorLabel.TextAlign = ContentAlignment.TopCenter;
            // 
            // bunifuButton28
            // 
            bunifuButton28.AllowAnimations = true;
            bunifuButton28.AllowMouseEffects = true;
            bunifuButton28.AllowToggling = false;
            bunifuButton28.AnimationSpeed = 200;
            bunifuButton28.AutoGenerateColors = false;
            bunifuButton28.AutoRoundBorders = false;
            bunifuButton28.AutoSizeLeftIcon = true;
            bunifuButton28.AutoSizeRightIcon = true;
            bunifuButton28.BackColor = Color.Transparent;
            bunifuButton28.BackColor1 = Color.SteelBlue;
            bunifuButton28.BackgroundImage = (Image)resources.GetObject("bunifuButton28.BackgroundImage");
            bunifuButton28.BackgroundImageLayout = ImageLayout.Zoom;
            bunifuButton28.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.ButtonText = "Quiz";
            bunifuButton28.ButtonTextMarginLeft = 0;
            bunifuButton28.ColorContrastOnClick = 45;
            bunifuButton28.ColorContrastOnHover = 45;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            bunifuButton28.CustomizableEdges = borderEdges8;
            bunifuButton28.DialogResult = DialogResult.None;
            bunifuButton28.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton28.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton28.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton28.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton28.Font = new Font("Segoe UI", 9F);
            bunifuButton28.ForeColor = Color.White;
            bunifuButton28.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton28.IconLeftCursor = Cursors.Default;
            bunifuButton28.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton28.IconMarginLeft = 11;
            bunifuButton28.IconPadding = 10;
            bunifuButton28.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton28.IconRightCursor = Cursors.Default;
            bunifuButton28.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton28.IconSize = 25;
            bunifuButton28.IdleBorderColor = Color.Azure;
            bunifuButton28.IdleBorderRadius = 30;
            bunifuButton28.IdleBorderThickness = 2;
            bunifuButton28.IdleFillColor = Color.SteelBlue;
            bunifuButton28.IdleIconLeftImage = null;
            bunifuButton28.IdleIconRightImage = null;
            bunifuButton28.IndicateFocus = false;
            bunifuButton28.Location = new Point(718, 564);
            bunifuButton28.Name = "bunifuButton28";
            bunifuButton28.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton28.OnDisabledState.BorderRadius = 30;
            bunifuButton28.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.OnDisabledState.BorderThickness = 2;
            bunifuButton28.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton28.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton28.OnDisabledState.IconLeftImage = null;
            bunifuButton28.OnDisabledState.IconRightImage = null;
            bunifuButton28.onHoverState.BorderColor = Color.Cyan;
            bunifuButton28.onHoverState.BorderRadius = 30;
            bunifuButton28.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.onHoverState.BorderThickness = 2;
            bunifuButton28.onHoverState.FillColor = Color.Cyan;
            bunifuButton28.onHoverState.ForeColor = Color.White;
            bunifuButton28.onHoverState.IconLeftImage = null;
            bunifuButton28.onHoverState.IconRightImage = null;
            bunifuButton28.OnIdleState.BorderColor = Color.Azure;
            bunifuButton28.OnIdleState.BorderRadius = 30;
            bunifuButton28.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.OnIdleState.BorderThickness = 2;
            bunifuButton28.OnIdleState.FillColor = Color.SteelBlue;
            bunifuButton28.OnIdleState.ForeColor = Color.White;
            bunifuButton28.OnIdleState.IconLeftImage = null;
            bunifuButton28.OnIdleState.IconRightImage = null;
            bunifuButton28.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton28.OnPressedState.BorderRadius = 30;
            bunifuButton28.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.OnPressedState.BorderThickness = 2;
            bunifuButton28.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton28.OnPressedState.ForeColor = Color.White;
            bunifuButton28.OnPressedState.IconLeftImage = null;
            bunifuButton28.OnPressedState.IconRightImage = null;
            bunifuButton28.Size = new Size(323, 51);
            bunifuButton28.TabIndex = 30;
            bunifuButton28.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton28.TextAlignment = HorizontalAlignment.Center;
            bunifuButton28.TextMarginLeft = 0;
            bunifuButton28.TextPadding = new Padding(0);
            bunifuButton28.UseDefaultRadiusAndThickness = true;
            bunifuButton28.Click += bunifuButton28_Click;
            // 
            // bunifuButton29
            // 
            bunifuButton29.AllowAnimations = true;
            bunifuButton29.AllowMouseEffects = true;
            bunifuButton29.AllowToggling = false;
            bunifuButton29.AnimationSpeed = 200;
            bunifuButton29.AutoGenerateColors = false;
            bunifuButton29.AutoRoundBorders = false;
            bunifuButton29.AutoSizeLeftIcon = true;
            bunifuButton29.AutoSizeRightIcon = true;
            bunifuButton29.BackColor = Color.Transparent;
            bunifuButton29.BackColor1 = Color.SteelBlue;
            bunifuButton29.BackgroundImage = (Image)resources.GetObject("bunifuButton29.BackgroundImage");
            bunifuButton29.BackgroundImageLayout = ImageLayout.Zoom;
            bunifuButton29.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton29.ButtonText = "Lịch nhóm";
            bunifuButton29.ButtonTextMarginLeft = 0;
            bunifuButton29.ColorContrastOnClick = 45;
            bunifuButton29.ColorContrastOnHover = 45;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            bunifuButton29.CustomizableEdges = borderEdges9;
            bunifuButton29.DialogResult = DialogResult.None;
            bunifuButton29.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton29.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton29.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton29.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton29.Font = new Font("Segoe UI", 9F);
            bunifuButton29.ForeColor = Color.White;
            bunifuButton29.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton29.IconLeftCursor = Cursors.Default;
            bunifuButton29.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton29.IconMarginLeft = 11;
            bunifuButton29.IconPadding = 10;
            bunifuButton29.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton29.IconRightCursor = Cursors.Default;
            bunifuButton29.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton29.IconSize = 25;
            bunifuButton29.IdleBorderColor = Color.Azure;
            bunifuButton29.IdleBorderRadius = 30;
            bunifuButton29.IdleBorderThickness = 2;
            bunifuButton29.IdleFillColor = Color.SteelBlue;
            bunifuButton29.IdleIconLeftImage = null;
            bunifuButton29.IdleIconRightImage = null;
            bunifuButton29.IndicateFocus = false;
            bunifuButton29.Location = new Point(718, 621);
            bunifuButton29.Name = "bunifuButton29";
            bunifuButton29.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton29.OnDisabledState.BorderRadius = 30;
            bunifuButton29.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton29.OnDisabledState.BorderThickness = 2;
            bunifuButton29.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton29.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton29.OnDisabledState.IconLeftImage = null;
            bunifuButton29.OnDisabledState.IconRightImage = null;
            bunifuButton29.onHoverState.BorderColor = Color.Cyan;
            bunifuButton29.onHoverState.BorderRadius = 30;
            bunifuButton29.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton29.onHoverState.BorderThickness = 2;
            bunifuButton29.onHoverState.FillColor = Color.Cyan;
            bunifuButton29.onHoverState.ForeColor = Color.White;
            bunifuButton29.onHoverState.IconLeftImage = null;
            bunifuButton29.onHoverState.IconRightImage = null;
            bunifuButton29.OnIdleState.BorderColor = Color.Azure;
            bunifuButton29.OnIdleState.BorderRadius = 30;
            bunifuButton29.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton29.OnIdleState.BorderThickness = 2;
            bunifuButton29.OnIdleState.FillColor = Color.SteelBlue;
            bunifuButton29.OnIdleState.ForeColor = Color.White;
            bunifuButton29.OnIdleState.IconLeftImage = null;
            bunifuButton29.OnIdleState.IconRightImage = null;
            bunifuButton29.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton29.OnPressedState.BorderRadius = 30;
            bunifuButton29.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton29.OnPressedState.BorderThickness = 2;
            bunifuButton29.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton29.OnPressedState.ForeColor = Color.White;
            bunifuButton29.OnPressedState.IconLeftImage = null;
            bunifuButton29.OnPressedState.IconRightImage = null;
            bunifuButton29.Size = new Size(323, 51);
            bunifuButton29.TabIndex = 31;
            bunifuButton29.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton29.TextAlignment = HorizontalAlignment.Center;
            bunifuButton29.TextMarginLeft = 0;
            bunifuButton29.TextPadding = new Padding(0);
            bunifuButton29.UseDefaultRadiusAndThickness = true;
            bunifuButton29.Click += bunifuButton29_Click;
            // 
            // FormNhom
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.LightBlue;
            ClientSize = new Size(1080, 674);
            Controls.Add(bunifuButton29);
            Controls.Add(bunifuButton28);
            Controls.Add(errorLabel);
            Controls.Add(bunifuButton26);
            Controls.Add(bunifuButton25);
            Controls.Add(bunifuButton22);
            Controls.Add(bunifuButton23);
            Controls.Add(bunifuPanel1);
            Controls.Add(textBox1);
            Controls.Add(richTextBox1);
            Name = "FormNhom";
            Text = "FormNhom";
            bunifuPanel1.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        private SaveFileDialog saveFileDialog1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton23;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        public ListView listView1;
        private TextBox textBox1;
        public RichTextBox richTextBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton24;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton25;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton26;
        private Label errorLabel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton27;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton28;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton29;
    }
}