namespace DangKi_DangNhap
{
    partial class MaHoaFile
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MaHoaFile));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            errorLabel = new Label();
            bunifuButton28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            save = new TextBox();
            tb_link = new TextBox();
            decrypt_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            encrypt_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            button1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            button4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            Key = new TextBox();
            bunifuPanel1.SuspendLayout();
            SuspendLayout();
            // 
            // bunifuPanel1
            // 
            bunifuPanel1.BackgroundColor = Color.OldLace;
            bunifuPanel1.BackgroundImage = (Image)resources.GetObject("bunifuPanel1.BackgroundImage");
            bunifuPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel1.BorderColor = Color.Navy;
            bunifuPanel1.BorderRadius = 50;
            bunifuPanel1.BorderThickness = 2;
            bunifuPanel1.Controls.Add(errorLabel);
            bunifuPanel1.Controls.Add(bunifuButton28);
            bunifuPanel1.Controls.Add(bunifuButton27);
            bunifuPanel1.Controls.Add(save);
            bunifuPanel1.Controls.Add(tb_link);
            bunifuPanel1.Controls.Add(decrypt_btn);
            bunifuPanel1.Controls.Add(encrypt_btn);
            bunifuPanel1.Controls.Add(button1);
            bunifuPanel1.Controls.Add(button4);
            bunifuPanel1.Controls.Add(bunifuButton22);
            bunifuPanel1.Controls.Add(Key);
            bunifuPanel1.Location = new Point(12, 12);
            bunifuPanel1.Name = "bunifuPanel1";
            bunifuPanel1.ShowBorders = true;
            bunifuPanel1.Size = new Size(776, 322);
            bunifuPanel1.TabIndex = 19;
            // 
            // errorLabel
            // 
            errorLabel.BackColor = Color.Transparent;
            errorLabel.Font = new Font("Segoe UI", 10.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            errorLabel.ForeColor = Color.Red;
            errorLabel.Location = new Point(202, 197);
            errorLabel.Name = "errorLabel";
            errorLabel.Size = new Size(330, 28);
            errorLabel.TabIndex = 30;
            errorLabel.Text = "errorLabel";
            errorLabel.TextAlign = ContentAlignment.TopCenter;
            // 
            // bunifuButton28
            // 
            bunifuButton28.AllowAnimations = true;
            bunifuButton28.AllowMouseEffects = true;
            bunifuButton28.AllowToggling = false;
            bunifuButton28.AnimationSpeed = 200;
            bunifuButton28.AutoGenerateColors = false;
            bunifuButton28.AutoRoundBorders = false;
            bunifuButton28.AutoSizeLeftIcon = true;
            bunifuButton28.AutoSizeRightIcon = true;
            bunifuButton28.BackColor = Color.Transparent;
            bunifuButton28.BackColor1 = Color.Transparent;
            bunifuButton28.BackgroundImage = (Image)resources.GetObject("bunifuButton28.BackgroundImage");
            bunifuButton28.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.ButtonText = "File nguồn";
            bunifuButton28.ButtonTextMarginLeft = 0;
            bunifuButton28.ColorContrastOnClick = 45;
            bunifuButton28.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            bunifuButton28.CustomizableEdges = borderEdges1;
            bunifuButton28.DialogResult = DialogResult.None;
            bunifuButton28.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton28.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton28.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton28.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton28.Font = new Font("Segoe UI", 13.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            bunifuButton28.ForeColor = Color.Black;
            bunifuButton28.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton28.IconLeftCursor = Cursors.Default;
            bunifuButton28.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton28.IconMarginLeft = 11;
            bunifuButton28.IconPadding = 10;
            bunifuButton28.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton28.IconRightCursor = Cursors.Default;
            bunifuButton28.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton28.IconSize = 25;
            bunifuButton28.IdleBorderColor = Color.DodgerBlue;
            bunifuButton28.IdleBorderRadius = 25;
            bunifuButton28.IdleBorderThickness = 1;
            bunifuButton28.IdleFillColor = Color.Transparent;
            bunifuButton28.IdleIconLeftImage = null;
            bunifuButton28.IdleIconRightImage = null;
            bunifuButton28.IndicateFocus = false;
            bunifuButton28.Location = new Point(11, 80);
            bunifuButton28.Name = "bunifuButton28";
            bunifuButton28.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton28.OnDisabledState.BorderRadius = 25;
            bunifuButton28.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.OnDisabledState.BorderThickness = 1;
            bunifuButton28.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton28.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton28.OnDisabledState.IconLeftImage = null;
            bunifuButton28.OnDisabledState.IconRightImage = null;
            bunifuButton28.onHoverState.BorderColor = Color.DodgerBlue;
            bunifuButton28.onHoverState.BorderRadius = 25;
            bunifuButton28.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.onHoverState.BorderThickness = 1;
            bunifuButton28.onHoverState.FillColor = Color.OldLace;
            bunifuButton28.onHoverState.ForeColor = Color.Black;
            bunifuButton28.onHoverState.IconLeftImage = null;
            bunifuButton28.onHoverState.IconRightImage = null;
            bunifuButton28.OnIdleState.BorderColor = Color.DodgerBlue;
            bunifuButton28.OnIdleState.BorderRadius = 25;
            bunifuButton28.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.OnIdleState.BorderThickness = 1;
            bunifuButton28.OnIdleState.FillColor = Color.Transparent;
            bunifuButton28.OnIdleState.ForeColor = Color.Black;
            bunifuButton28.OnIdleState.IconLeftImage = null;
            bunifuButton28.OnIdleState.IconRightImage = null;
            bunifuButton28.OnPressedState.BorderColor = Color.DodgerBlue;
            bunifuButton28.OnPressedState.BorderRadius = 25;
            bunifuButton28.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton28.OnPressedState.BorderThickness = 1;
            bunifuButton28.OnPressedState.FillColor = Color.OldLace;
            bunifuButton28.OnPressedState.ForeColor = Color.Black;
            bunifuButton28.OnPressedState.IconLeftImage = null;
            bunifuButton28.OnPressedState.IconRightImage = null;
            bunifuButton28.Size = new Size(133, 49);
            bunifuButton28.TabIndex = 27;
            bunifuButton28.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton28.TextAlignment = HorizontalAlignment.Center;
            bunifuButton28.TextMarginLeft = 0;
            bunifuButton28.TextPadding = new Padding(0);
            bunifuButton28.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton27
            // 
            bunifuButton27.AllowAnimations = true;
            bunifuButton27.AllowMouseEffects = true;
            bunifuButton27.AllowToggling = false;
            bunifuButton27.AnimationSpeed = 200;
            bunifuButton27.AutoGenerateColors = false;
            bunifuButton27.AutoRoundBorders = false;
            bunifuButton27.AutoSizeLeftIcon = true;
            bunifuButton27.AutoSizeRightIcon = true;
            bunifuButton27.BackColor = Color.Transparent;
            bunifuButton27.BackColor1 = Color.Transparent;
            bunifuButton27.BackgroundImage = (Image)resources.GetObject("bunifuButton27.BackgroundImage");
            bunifuButton27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.ButtonText = "Lưu vào";
            bunifuButton27.ButtonTextMarginLeft = 0;
            bunifuButton27.ColorContrastOnClick = 45;
            bunifuButton27.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            bunifuButton27.CustomizableEdges = borderEdges2;
            bunifuButton27.DialogResult = DialogResult.None;
            bunifuButton27.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton27.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton27.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton27.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton27.Font = new Font("Segoe UI", 13.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            bunifuButton27.ForeColor = Color.Black;
            bunifuButton27.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton27.IconLeftCursor = Cursors.Default;
            bunifuButton27.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton27.IconMarginLeft = 11;
            bunifuButton27.IconPadding = 10;
            bunifuButton27.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton27.IconRightCursor = Cursors.Default;
            bunifuButton27.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton27.IconSize = 25;
            bunifuButton27.IdleBorderColor = Color.DodgerBlue;
            bunifuButton27.IdleBorderRadius = 25;
            bunifuButton27.IdleBorderThickness = 1;
            bunifuButton27.IdleFillColor = Color.Transparent;
            bunifuButton27.IdleIconLeftImage = null;
            bunifuButton27.IdleIconRightImage = null;
            bunifuButton27.IndicateFocus = false;
            bunifuButton27.Location = new Point(11, 136);
            bunifuButton27.Name = "bunifuButton27";
            bunifuButton27.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton27.OnDisabledState.BorderRadius = 25;
            bunifuButton27.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnDisabledState.BorderThickness = 1;
            bunifuButton27.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton27.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton27.OnDisabledState.IconLeftImage = null;
            bunifuButton27.OnDisabledState.IconRightImage = null;
            bunifuButton27.onHoverState.BorderColor = Color.DodgerBlue;
            bunifuButton27.onHoverState.BorderRadius = 25;
            bunifuButton27.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.onHoverState.BorderThickness = 1;
            bunifuButton27.onHoverState.FillColor = Color.OldLace;
            bunifuButton27.onHoverState.ForeColor = Color.Black;
            bunifuButton27.onHoverState.IconLeftImage = null;
            bunifuButton27.onHoverState.IconRightImage = null;
            bunifuButton27.OnIdleState.BorderColor = Color.DodgerBlue;
            bunifuButton27.OnIdleState.BorderRadius = 25;
            bunifuButton27.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnIdleState.BorderThickness = 1;
            bunifuButton27.OnIdleState.FillColor = Color.Transparent;
            bunifuButton27.OnIdleState.ForeColor = Color.Black;
            bunifuButton27.OnIdleState.IconLeftImage = null;
            bunifuButton27.OnIdleState.IconRightImage = null;
            bunifuButton27.OnPressedState.BorderColor = Color.DodgerBlue;
            bunifuButton27.OnPressedState.BorderRadius = 25;
            bunifuButton27.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnPressedState.BorderThickness = 1;
            bunifuButton27.OnPressedState.FillColor = Color.OldLace;
            bunifuButton27.OnPressedState.ForeColor = Color.Black;
            bunifuButton27.OnPressedState.IconLeftImage = null;
            bunifuButton27.OnPressedState.IconRightImage = null;
            bunifuButton27.Size = new Size(133, 49);
            bunifuButton27.TabIndex = 26;
            bunifuButton27.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton27.TextAlignment = HorizontalAlignment.Center;
            bunifuButton27.TextMarginLeft = 0;
            bunifuButton27.TextPadding = new Padding(0);
            bunifuButton27.UseDefaultRadiusAndThickness = true;
            // 
            // save
            // 
            save.Font = new Font("Segoe UI", 13.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            save.Location = new Point(150, 136);
            save.Multiline = true;
            save.Name = "save";
            save.Size = new Size(506, 48);
            save.TabIndex = 25;
            // 
            // tb_link
            // 
            tb_link.Font = new Font("Segoe UI", 13.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            tb_link.Location = new Point(150, 81);
            tb_link.Multiline = true;
            tb_link.Name = "tb_link";
            tb_link.Size = new Size(506, 48);
            tb_link.TabIndex = 24;
            // 
            // decrypt_btn
            // 
            decrypt_btn.AllowAnimations = true;
            decrypt_btn.AllowMouseEffects = true;
            decrypt_btn.AllowToggling = false;
            decrypt_btn.AnimationSpeed = 200;
            decrypt_btn.AutoGenerateColors = false;
            decrypt_btn.AutoRoundBorders = false;
            decrypt_btn.AutoSizeLeftIcon = true;
            decrypt_btn.AutoSizeRightIcon = true;
            decrypt_btn.BackColor = Color.Transparent;
            decrypt_btn.BackColor1 = Color.SteelBlue;
            decrypt_btn.BackgroundImage = (Image)resources.GetObject("decrypt_btn.BackgroundImage");
            decrypt_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            decrypt_btn.ButtonText = "Giải mã";
            decrypt_btn.ButtonTextMarginLeft = 0;
            decrypt_btn.ColorContrastOnClick = 45;
            decrypt_btn.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            decrypt_btn.CustomizableEdges = borderEdges3;
            decrypt_btn.DialogResult = DialogResult.None;
            decrypt_btn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            decrypt_btn.DisabledFillColor = Color.FromArgb(204, 204, 204);
            decrypt_btn.DisabledForecolor = Color.FromArgb(168, 160, 168);
            decrypt_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            decrypt_btn.Font = new Font("Segoe UI", 9F);
            decrypt_btn.ForeColor = Color.White;
            decrypt_btn.IconLeftAlign = ContentAlignment.MiddleLeft;
            decrypt_btn.IconLeftCursor = Cursors.Default;
            decrypt_btn.IconLeftPadding = new Padding(11, 3, 3, 3);
            decrypt_btn.IconMarginLeft = 11;
            decrypt_btn.IconPadding = 10;
            decrypt_btn.IconRightAlign = ContentAlignment.MiddleRight;
            decrypt_btn.IconRightCursor = Cursors.Default;
            decrypt_btn.IconRightPadding = new Padding(3, 3, 7, 3);
            decrypt_btn.IconSize = 25;
            decrypt_btn.IdleBorderColor = Color.Azure;
            decrypt_btn.IdleBorderRadius = 45;
            decrypt_btn.IdleBorderThickness = 2;
            decrypt_btn.IdleFillColor = Color.SteelBlue;
            decrypt_btn.IdleIconLeftImage = null;
            decrypt_btn.IdleIconRightImage = null;
            decrypt_btn.IndicateFocus = false;
            decrypt_btn.Location = new Point(388, 245);
            decrypt_btn.Name = "decrypt_btn";
            decrypt_btn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            decrypt_btn.OnDisabledState.BorderRadius = 45;
            decrypt_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            decrypt_btn.OnDisabledState.BorderThickness = 2;
            decrypt_btn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            decrypt_btn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            decrypt_btn.OnDisabledState.IconLeftImage = null;
            decrypt_btn.OnDisabledState.IconRightImage = null;
            decrypt_btn.onHoverState.BorderColor = Color.Cyan;
            decrypt_btn.onHoverState.BorderRadius = 45;
            decrypt_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            decrypt_btn.onHoverState.BorderThickness = 2;
            decrypt_btn.onHoverState.FillColor = Color.Cyan;
            decrypt_btn.onHoverState.ForeColor = Color.White;
            decrypt_btn.onHoverState.IconLeftImage = null;
            decrypt_btn.onHoverState.IconRightImage = null;
            decrypt_btn.OnIdleState.BorderColor = Color.Azure;
            decrypt_btn.OnIdleState.BorderRadius = 45;
            decrypt_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            decrypt_btn.OnIdleState.BorderThickness = 2;
            decrypt_btn.OnIdleState.FillColor = Color.SteelBlue;
            decrypt_btn.OnIdleState.ForeColor = Color.White;
            decrypt_btn.OnIdleState.IconLeftImage = null;
            decrypt_btn.OnIdleState.IconRightImage = null;
            decrypt_btn.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            decrypt_btn.OnPressedState.BorderRadius = 45;
            decrypt_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            decrypt_btn.OnPressedState.BorderThickness = 2;
            decrypt_btn.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            decrypt_btn.OnPressedState.ForeColor = Color.White;
            decrypt_btn.OnPressedState.IconLeftImage = null;
            decrypt_btn.OnPressedState.IconRightImage = null;
            decrypt_btn.Size = new Size(174, 49);
            decrypt_btn.TabIndex = 23;
            decrypt_btn.TextAlign = ContentAlignment.MiddleCenter;
            decrypt_btn.TextAlignment = HorizontalAlignment.Center;
            decrypt_btn.TextMarginLeft = 0;
            decrypt_btn.TextPadding = new Padding(0);
            decrypt_btn.UseDefaultRadiusAndThickness = true;
            decrypt_btn.Click += decrypt_btn_Click;
            // 
            // encrypt_btn
            // 
            encrypt_btn.AllowAnimations = true;
            encrypt_btn.AllowMouseEffects = true;
            encrypt_btn.AllowToggling = false;
            encrypt_btn.AnimationSpeed = 200;
            encrypt_btn.AutoGenerateColors = false;
            encrypt_btn.AutoRoundBorders = false;
            encrypt_btn.AutoSizeLeftIcon = true;
            encrypt_btn.AutoSizeRightIcon = true;
            encrypt_btn.BackColor = Color.Transparent;
            encrypt_btn.BackColor1 = Color.SteelBlue;
            encrypt_btn.BackgroundImage = (Image)resources.GetObject("encrypt_btn.BackgroundImage");
            encrypt_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            encrypt_btn.ButtonText = "Mã hóa";
            encrypt_btn.ButtonTextMarginLeft = 0;
            encrypt_btn.ColorContrastOnClick = 45;
            encrypt_btn.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            encrypt_btn.CustomizableEdges = borderEdges4;
            encrypt_btn.DialogResult = DialogResult.None;
            encrypt_btn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            encrypt_btn.DisabledFillColor = Color.FromArgb(204, 204, 204);
            encrypt_btn.DisabledForecolor = Color.FromArgb(168, 160, 168);
            encrypt_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            encrypt_btn.Font = new Font("Segoe UI", 9F);
            encrypt_btn.ForeColor = Color.White;
            encrypt_btn.IconLeftAlign = ContentAlignment.MiddleLeft;
            encrypt_btn.IconLeftCursor = Cursors.Default;
            encrypt_btn.IconLeftPadding = new Padding(11, 3, 3, 3);
            encrypt_btn.IconMarginLeft = 11;
            encrypt_btn.IconPadding = 10;
            encrypt_btn.IconRightAlign = ContentAlignment.MiddleRight;
            encrypt_btn.IconRightCursor = Cursors.Default;
            encrypt_btn.IconRightPadding = new Padding(3, 3, 7, 3);
            encrypt_btn.IconSize = 25;
            encrypt_btn.IdleBorderColor = Color.Azure;
            encrypt_btn.IdleBorderRadius = 45;
            encrypt_btn.IdleBorderThickness = 2;
            encrypt_btn.IdleFillColor = Color.SteelBlue;
            encrypt_btn.IdleIconLeftImage = null;
            encrypt_btn.IdleIconRightImage = null;
            encrypt_btn.IndicateFocus = false;
            encrypt_btn.Location = new Point(168, 245);
            encrypt_btn.Name = "encrypt_btn";
            encrypt_btn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            encrypt_btn.OnDisabledState.BorderRadius = 45;
            encrypt_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            encrypt_btn.OnDisabledState.BorderThickness = 2;
            encrypt_btn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            encrypt_btn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            encrypt_btn.OnDisabledState.IconLeftImage = null;
            encrypt_btn.OnDisabledState.IconRightImage = null;
            encrypt_btn.onHoverState.BorderColor = Color.Cyan;
            encrypt_btn.onHoverState.BorderRadius = 45;
            encrypt_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            encrypt_btn.onHoverState.BorderThickness = 2;
            encrypt_btn.onHoverState.FillColor = Color.Cyan;
            encrypt_btn.onHoverState.ForeColor = Color.White;
            encrypt_btn.onHoverState.IconLeftImage = null;
            encrypt_btn.onHoverState.IconRightImage = null;
            encrypt_btn.OnIdleState.BorderColor = Color.Azure;
            encrypt_btn.OnIdleState.BorderRadius = 45;
            encrypt_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            encrypt_btn.OnIdleState.BorderThickness = 2;
            encrypt_btn.OnIdleState.FillColor = Color.SteelBlue;
            encrypt_btn.OnIdleState.ForeColor = Color.White;
            encrypt_btn.OnIdleState.IconLeftImage = null;
            encrypt_btn.OnIdleState.IconRightImage = null;
            encrypt_btn.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            encrypt_btn.OnPressedState.BorderRadius = 45;
            encrypt_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            encrypt_btn.OnPressedState.BorderThickness = 2;
            encrypt_btn.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            encrypt_btn.OnPressedState.ForeColor = Color.White;
            encrypt_btn.OnPressedState.IconLeftImage = null;
            encrypt_btn.OnPressedState.IconRightImage = null;
            encrypt_btn.Size = new Size(174, 49);
            encrypt_btn.TabIndex = 22;
            encrypt_btn.TextAlign = ContentAlignment.MiddleCenter;
            encrypt_btn.TextAlignment = HorizontalAlignment.Center;
            encrypt_btn.TextMarginLeft = 0;
            encrypt_btn.TextPadding = new Padding(0);
            encrypt_btn.UseDefaultRadiusAndThickness = true;
            encrypt_btn.Click += encrypt_btn_Click;
            // 
            // button1
            // 
            button1.AllowAnimations = true;
            button1.AllowMouseEffects = true;
            button1.AllowToggling = false;
            button1.AnimationSpeed = 200;
            button1.AutoGenerateColors = false;
            button1.AutoRoundBorders = false;
            button1.AutoSizeLeftIcon = true;
            button1.AutoSizeRightIcon = true;
            button1.BackColor = Color.Transparent;
            button1.BackColor1 = Color.SteelBlue;
            button1.BackgroundImage = (Image)resources.GetObject("button1.BackgroundImage");
            button1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button1.ButtonText = "Chọn";
            button1.ButtonTextMarginLeft = 0;
            button1.ColorContrastOnClick = 45;
            button1.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            button1.CustomizableEdges = borderEdges5;
            button1.DialogResult = DialogResult.None;
            button1.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            button1.DisabledFillColor = Color.FromArgb(204, 204, 204);
            button1.DisabledForecolor = Color.FromArgb(168, 160, 168);
            button1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            button1.Font = new Font("Segoe UI", 9F);
            button1.ForeColor = Color.White;
            button1.IconLeftAlign = ContentAlignment.MiddleLeft;
            button1.IconLeftCursor = Cursors.Default;
            button1.IconLeftPadding = new Padding(11, 3, 3, 3);
            button1.IconMarginLeft = 11;
            button1.IconPadding = 10;
            button1.IconRightAlign = ContentAlignment.MiddleRight;
            button1.IconRightCursor = Cursors.Default;
            button1.IconRightPadding = new Padding(3, 3, 7, 3);
            button1.IconSize = 25;
            button1.IdleBorderColor = Color.Azure;
            button1.IdleBorderRadius = 45;
            button1.IdleBorderThickness = 2;
            button1.IdleFillColor = Color.SteelBlue;
            button1.IdleIconLeftImage = null;
            button1.IdleIconRightImage = null;
            button1.IndicateFocus = false;
            button1.Location = new Point(662, 135);
            button1.Name = "button1";
            button1.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            button1.OnDisabledState.BorderRadius = 45;
            button1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button1.OnDisabledState.BorderThickness = 2;
            button1.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            button1.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            button1.OnDisabledState.IconLeftImage = null;
            button1.OnDisabledState.IconRightImage = null;
            button1.onHoverState.BorderColor = Color.Cyan;
            button1.onHoverState.BorderRadius = 45;
            button1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button1.onHoverState.BorderThickness = 2;
            button1.onHoverState.FillColor = Color.Cyan;
            button1.onHoverState.ForeColor = Color.White;
            button1.onHoverState.IconLeftImage = null;
            button1.onHoverState.IconRightImage = null;
            button1.OnIdleState.BorderColor = Color.Azure;
            button1.OnIdleState.BorderRadius = 45;
            button1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button1.OnIdleState.BorderThickness = 2;
            button1.OnIdleState.FillColor = Color.SteelBlue;
            button1.OnIdleState.ForeColor = Color.White;
            button1.OnIdleState.IconLeftImage = null;
            button1.OnIdleState.IconRightImage = null;
            button1.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            button1.OnPressedState.BorderRadius = 45;
            button1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button1.OnPressedState.BorderThickness = 2;
            button1.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            button1.OnPressedState.ForeColor = Color.White;
            button1.OnPressedState.IconLeftImage = null;
            button1.OnPressedState.IconRightImage = null;
            button1.Size = new Size(98, 49);
            button1.TabIndex = 20;
            button1.TextAlign = ContentAlignment.MiddleCenter;
            button1.TextAlignment = HorizontalAlignment.Center;
            button1.TextMarginLeft = 0;
            button1.TextPadding = new Padding(0);
            button1.UseDefaultRadiusAndThickness = true;
            button1.Click += button1_Click;
            // 
            // button4
            // 
            button4.AllowAnimations = true;
            button4.AllowMouseEffects = true;
            button4.AllowToggling = false;
            button4.AnimationSpeed = 200;
            button4.AutoGenerateColors = false;
            button4.AutoRoundBorders = false;
            button4.AutoSizeLeftIcon = true;
            button4.AutoSizeRightIcon = true;
            button4.BackColor = Color.Transparent;
            button4.BackColor1 = Color.SteelBlue;
            button4.BackgroundImage = (Image)resources.GetObject("button4.BackgroundImage");
            button4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button4.ButtonText = "Chọn";
            button4.ButtonTextMarginLeft = 0;
            button4.ColorContrastOnClick = 45;
            button4.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            button4.CustomizableEdges = borderEdges6;
            button4.DialogResult = DialogResult.None;
            button4.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            button4.DisabledFillColor = Color.FromArgb(204, 204, 204);
            button4.DisabledForecolor = Color.FromArgb(168, 160, 168);
            button4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            button4.Font = new Font("Segoe UI", 9F);
            button4.ForeColor = Color.White;
            button4.IconLeftAlign = ContentAlignment.MiddleLeft;
            button4.IconLeftCursor = Cursors.Default;
            button4.IconLeftPadding = new Padding(11, 3, 3, 3);
            button4.IconMarginLeft = 11;
            button4.IconPadding = 10;
            button4.IconRightAlign = ContentAlignment.MiddleRight;
            button4.IconRightCursor = Cursors.Default;
            button4.IconRightPadding = new Padding(3, 3, 7, 3);
            button4.IconSize = 25;
            button4.IdleBorderColor = Color.Azure;
            button4.IdleBorderRadius = 45;
            button4.IdleBorderThickness = 2;
            button4.IdleFillColor = Color.SteelBlue;
            button4.IdleIconLeftImage = null;
            button4.IdleIconRightImage = null;
            button4.IndicateFocus = false;
            button4.Location = new Point(662, 82);
            button4.Name = "button4";
            button4.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            button4.OnDisabledState.BorderRadius = 45;
            button4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button4.OnDisabledState.BorderThickness = 2;
            button4.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            button4.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            button4.OnDisabledState.IconLeftImage = null;
            button4.OnDisabledState.IconRightImage = null;
            button4.onHoverState.BorderColor = Color.Cyan;
            button4.onHoverState.BorderRadius = 45;
            button4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button4.onHoverState.BorderThickness = 2;
            button4.onHoverState.FillColor = Color.Cyan;
            button4.onHoverState.ForeColor = Color.White;
            button4.onHoverState.IconLeftImage = null;
            button4.onHoverState.IconRightImage = null;
            button4.OnIdleState.BorderColor = Color.Azure;
            button4.OnIdleState.BorderRadius = 45;
            button4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button4.OnIdleState.BorderThickness = 2;
            button4.OnIdleState.FillColor = Color.SteelBlue;
            button4.OnIdleState.ForeColor = Color.White;
            button4.OnIdleState.IconLeftImage = null;
            button4.OnIdleState.IconRightImage = null;
            button4.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            button4.OnPressedState.BorderRadius = 45;
            button4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            button4.OnPressedState.BorderThickness = 2;
            button4.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            button4.OnPressedState.ForeColor = Color.White;
            button4.OnPressedState.IconLeftImage = null;
            button4.OnPressedState.IconRightImage = null;
            button4.Size = new Size(98, 49);
            button4.TabIndex = 21;
            button4.TextAlign = ContentAlignment.MiddleCenter;
            button4.TextAlignment = HorizontalAlignment.Center;
            button4.TextMarginLeft = 0;
            button4.TextPadding = new Padding(0);
            button4.UseDefaultRadiusAndThickness = true;
            button4.Click += button4_Click;
            // 
            // bunifuButton22
            // 
            bunifuButton22.AllowAnimations = true;
            bunifuButton22.AllowMouseEffects = true;
            bunifuButton22.AllowToggling = false;
            bunifuButton22.AnimationSpeed = 200;
            bunifuButton22.AutoGenerateColors = false;
            bunifuButton22.AutoRoundBorders = false;
            bunifuButton22.AutoSizeLeftIcon = true;
            bunifuButton22.AutoSizeRightIcon = true;
            bunifuButton22.BackColor = Color.Transparent;
            bunifuButton22.BackColor1 = Color.Transparent;
            bunifuButton22.BackgroundImage = (Image)resources.GetObject("bunifuButton22.BackgroundImage");
            bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.ButtonText = "Mật khẩu";
            bunifuButton22.ButtonTextMarginLeft = 0;
            bunifuButton22.ColorContrastOnClick = 45;
            bunifuButton22.ColorContrastOnHover = 45;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            bunifuButton22.CustomizableEdges = borderEdges7;
            bunifuButton22.DialogResult = DialogResult.None;
            bunifuButton22.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton22.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton22.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton22.Font = new Font("Segoe UI", 13.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            bunifuButton22.ForeColor = Color.Black;
            bunifuButton22.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton22.IconLeftCursor = Cursors.Default;
            bunifuButton22.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton22.IconMarginLeft = 11;
            bunifuButton22.IconPadding = 10;
            bunifuButton22.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton22.IconRightCursor = Cursors.Default;
            bunifuButton22.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton22.IconSize = 25;
            bunifuButton22.IdleBorderColor = Color.DodgerBlue;
            bunifuButton22.IdleBorderRadius = 25;
            bunifuButton22.IdleBorderThickness = 1;
            bunifuButton22.IdleFillColor = Color.Transparent;
            bunifuButton22.IdleIconLeftImage = null;
            bunifuButton22.IdleIconRightImage = null;
            bunifuButton22.IndicateFocus = false;
            bunifuButton22.Location = new Point(11, 25);
            bunifuButton22.Name = "bunifuButton22";
            bunifuButton22.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton22.OnDisabledState.BorderRadius = 25;
            bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnDisabledState.BorderThickness = 1;
            bunifuButton22.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton22.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton22.OnDisabledState.IconLeftImage = null;
            bunifuButton22.OnDisabledState.IconRightImage = null;
            bunifuButton22.onHoverState.BorderColor = Color.DodgerBlue;
            bunifuButton22.onHoverState.BorderRadius = 25;
            bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.onHoverState.BorderThickness = 1;
            bunifuButton22.onHoverState.FillColor = Color.OldLace;
            bunifuButton22.onHoverState.ForeColor = Color.Black;
            bunifuButton22.onHoverState.IconLeftImage = null;
            bunifuButton22.onHoverState.IconRightImage = null;
            bunifuButton22.OnIdleState.BorderColor = Color.DodgerBlue;
            bunifuButton22.OnIdleState.BorderRadius = 25;
            bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnIdleState.BorderThickness = 1;
            bunifuButton22.OnIdleState.FillColor = Color.Transparent;
            bunifuButton22.OnIdleState.ForeColor = Color.Black;
            bunifuButton22.OnIdleState.IconLeftImage = null;
            bunifuButton22.OnIdleState.IconRightImage = null;
            bunifuButton22.OnPressedState.BorderColor = Color.DodgerBlue;
            bunifuButton22.OnPressedState.BorderRadius = 25;
            bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnPressedState.BorderThickness = 1;
            bunifuButton22.OnPressedState.FillColor = Color.OldLace;
            bunifuButton22.OnPressedState.ForeColor = Color.Black;
            bunifuButton22.OnPressedState.IconLeftImage = null;
            bunifuButton22.OnPressedState.IconRightImage = null;
            bunifuButton22.Size = new Size(133, 49);
            bunifuButton22.TabIndex = 13;
            bunifuButton22.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton22.TextAlignment = HorizontalAlignment.Center;
            bunifuButton22.TextMarginLeft = 0;
            bunifuButton22.TextPadding = new Padding(0);
            bunifuButton22.UseDefaultRadiusAndThickness = true;
            // 
            // Key
            // 
            Key.Font = new Font("Segoe UI", 13.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            Key.Location = new Point(150, 25);
            Key.Multiline = true;
            Key.Name = "Key";
            Key.Size = new Size(506, 48);
            Key.TabIndex = 0;
            // 
            // MaHoaFile
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.SteelBlue;
            ClientSize = new Size(801, 348);
            Controls.Add(bunifuPanel1);
            Name = "MaHoaFile";
            Text = "MaHoaFile";
            bunifuPanel1.ResumeLayout(false);
            bunifuPanel1.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private TextBox Key;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton28;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton27;
        private TextBox save;
        private TextBox tb_link;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 decrypt_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 encrypt_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button4;
        private Label errorLabel;
    }
}